CAT_LIST = ['bid bot abuse',
            'bid bot misuse',
            'collusive voting',
            'comment self-vote violation',
            'comment spam',
            'copy/paste',
            'death threats',
            'failure to tag nsfw',
            'identity theft',
            'manipulation',
            'phishing',
            'plagiarism',
            'post farming',
            'scam',
            'spam',
            'tag abuse',
            'tag misuse',
            'testing for rewards',
            'threat',
            'vote abuse',
            'vote farming',
            ]  # Because the categories are sorted alphabetically, comment spam will be found before spam is, causing everything to work out as intended.

CAT_DESCRIPTION = {'bid bot abuse' : 'description',
                   'bid bot misuse' : 'description',
                   'collusive voting' : 'description',
                   'comment self-vote violation' : 'description',
                   'comment spam' : 'description',
                   'copy/paste' : 'description',
                   'death threats' : 'description',
                   'failure to tag nsfw' : 'description',
                   'identity theft' : 'description',
                   'manipulation' : 'description',
                   'phishing' : 'description',
                   'plagiarism' : 'description',
                   'post farming' : 'description',
                   'scam' : 'description',
                   'spam' : 'description',
                   'tag abuse' : 'description',
                   'tag misuse' : 'description',
                   'testing for rewards' : 'description',
                   'threat' : 'description',
                   'vote abuse' : 'description',
                   'vote farming' : 'description',
}
