categories = ['bid bot abuse',
              'collusive voting',
              'comment self-vote violation',
              'comment spam',
              'copy/paste',
              'failure to tag nsfw',
              'identity theft',
              'manipulation',
              'phishing',
              'plagiarism',
              'scam',
              'spam',
              'tag abuse',
              'tag misuse',
              'testing for rewards',
              'threat',
              'vote abuse',
              'vote farming']  # Because the categories are sorted alphabetically, comment spam will be found before spam is, causing everything to work out as intended.  # Because the categories are sorted alphabetically, comment spam will be found before spam is, causing everything to work out as intended.

CAT_DESCRIPTION = {'bid bot abuse' : '\n* bid bot abuse\nYou bought votes to increase the rewards of your post above the value of its content.',
                   'collusive voting' : '\ndescription placeholder',
                   'comment self-vote violation' : '\n* comment self-vote violation\nYou left a comment favorable about the post, you didn\'t upvote the post, and upvoted your own comment.',
                   'comment spam' : '\n* comment spam\nYour comment has been repeated multiple times without regard to the post.',
                   'copy/paste' : '\n* copy/paste\nYour post mostly contains copied material from a source or stock content and is not your original work.',
                   'failure to tag nsfw' : '\n* failure to tag nsfw\nYour post should be tagged NSFW when it contains nudity, gore, extreme violence or anything inappropriate for general public viewing.',
                   'identity theft' : '\n* identity theft\nYou are pretending to be someone you are not.',
                   'manipulation' : '\ndescription placeholder',
                   'phishing' : '\n* phishing\nYou are trying to steal account keys, password or credentials.',
                   'plagiarism' : '\n* plagiarism\nYou are posting content that is not yours by copying it without sourcing or manipulating it to pass plagiarism tools.',
                   'post farming' : '\ndescription placeholder',
                   'scam' : '\n* scam\nThis post is a scam, designed to trick or defraud others.',
                   'spam' : '\n* spam\nYou are repetitively posting the same content or recyling contents after a period of time.',
                   'tag abuse' : '\n* tag abuse\nYou used tags irrelevant to your content or used the introduceyourself tag more than twice.',
                   'tag misuse' : '\ndescription placeholder',
                   'testing for rewards' : '\n* testing for rewards\nYou claimed to be “testing” but did not decline rewards.',
                   'threat' : '\ndescription placeholder',
                   'vote abuse' : '\ndescription placeholder',
                   'vote farming' : '\n* vote farming\nYou\'re churning out content (often low quality), in quick successions with abnormal number and/or upvote size.',
}
